// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxcbpmqsbcpsljwwwwyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Y2JwbXFzYmNwc2xqd3d3d3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjY5MDIsImV4cCI6MjA2Mzg0MjkwMn0.cbcKbYLZz8SGNO84yNy15AQCo1Ldhn1apoLtMDWqrxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);